apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-data
  namespace: cdielk
  labels:
    app: elasticsearch
    role: data
spec:
  serviceName: elasticsearch-data
  selector:
    matchLabels:
      app: elasticsearch
      role: data
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
        role: data
    spec:  
      serviceAccountName: elkserviceaccount
      volumes:
        - name: esconfig
          configMap:
            name: es-data-config
        - name: elkvolume
          persistentVolumeClaim:
           claimName: elkpvc
        - name: elasticsearch-cert
          secret:
            secretName: elasticsearch-cert
        - name: elasticsearch-keystore
          secret:
            secretName: elasticsearch-keystore
        - name: oidc-cert
          secret:
            secretName: oidc-cert
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: priviledge
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "chmod -R 777 /usr/share"]
        volumeMounts:
        - name: elkvolume
          mountPath: /usr/share
      containers:
      - name: elasticsearch-data
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        ports:
        - name: http
          containerPort: 9200
        - name: transport
          containerPort: 9300
        env:
        - name: CLUSTER_NAME
          value: elasticsearch
        - name: NODE_NAME
          value: elasticsearch-data
        - name: NODE_LIST
          value: elasticsearch-master,elasticsearch-data,elasticsearch-ingest
        - name: MASTER_NODES
          value: elasticsearch-master
        - name: "ES_JAVA_OPTS"
          value: "-Xms2g -Xmx2g"
        - name: ELASTIC_USERNAME
          value: elastic
        - name: ELASTIC_PASSWORD
          valueFrom:
           secretKeyRef:
             name: mysecret
             key: password
        volumeMounts:
          - name: elkvolume
            mountPath: /usr/share/elasticsearch/data
          - name: esconfig
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            readOnly: true
            subPath: elasticsearch.yml
          - name: elasticsearch-cert
            mountPath: /usr/share/elasticsearch/config/cert
            readOnly: true
          - name: elasticsearch-keystore
            mountPath: /usr/share/elasticsearch/config/elasticsearch.keystore
            subPath: elasticsearch.keystore
          - name: oidc-cert
            mountPath: /usr/share/elasticsearch/config/oidc
        resources:
          requests:
            memory: "1Gi"
